server:
   port: 9005
example:
  baseUrl: http://localhost:9004
  oauth2:
    client:
      grantType: client_credentials
      clientId: rajesh
      clientSecret: rajesh
      accessTokenUri: http://localhost:9003/oauth/token
      scope: resource-server-read